name: fest

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.1
  riverpod: ^1.0.0-dev.1
  path: ^1.8.0
  cli_util: ^0.3.0
  test: ^1.17.8
  freezed: ^0.14.2
  json_annotation: ^4.0.0

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^2.0.4

executables:
  fest: main
