name: dart_test_adapter
description: Provides a Dart API for interacting with `dart test`/`flutter test` programatically

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  args: ^2.1.1
  path: ^1.8.0
  cli_util: ^0.3.0
  test: ^1.17.8
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0

dev_dependencies:
  freezed: ^1.1.1
  json_serializable: ^6.1.3
  build_runner: ^2.1.7

executables:
  fest: main
