name: spec_cli

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ansi_styles: 0.3.1-dev.0
  args: ^2.1.1
  dart_test_adapter:
    path: ../dart_test_adapter
  riverpod: ^1.0.0
  path: ^1.8.0
  cli_util: ^0.3.0
  test: ^1.17.8
  freezed_annotation: ^0.14.3
  dart_console: ^1.0.0

dev_dependencies:
  freezed: ^0.14.5
  json_serializable: ^5.0.0
  build_runner: ^2.0.4
  test_descriptor: ^2.0.0

executables:
  spec: main