name: spec_cli

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ansi_styles: ^0.3.1
  args: ^2.1.1
  cli_util: ^0.3.0
  collection: ^1.15.0
  dart_console: ^1.0.0
  dart_test_adapter:
    path: ../dart_test_adapter
  duration: ^3.0.8
  freezed_annotation: ^1.1.0
  melos: ^1.1.0
  meta: ^1.7.0
  path: ^1.8.0
  pubspec: ^2.0.1
  riverpod: ^2.0.0-dev.0
  test: ^1.17.8

dev_dependencies:
  build_runner: ^2.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.3

executables:
  spec: main